module ConsentEngine
  module Domain
    module ReasonCode
      AUTHORIZED = "AUTHORIZED"
      EMERGENCY_AUTHORIZED = "EMERGENCY_AUTHORIZED"

      NO_CONSENT = "NO_CONSENT"
      SCOPE_NOT_GRANTED = "SCOPE_NOT_GRANTED"
      NOT_YET_VALID = "NOT_YET_VALID"
      EXPIRED = "EXPIRED"
      REVOKED = "REVOKED"
      WITNESS_MISSING = "WITNESS_MISSING"

      DELEGATION_WITHOUT_SOURCE = "DELEGATION_WITHOUT_SOURCE"
      DELEGATION_BROADER_THAN_SOURCE = "DELEGATION_BROADER_THAN_SOURCE"
      DELEGATION_DURATION_EXCEEDS_SOURCE = "DELEGATION_DURATION_EXCEEDS_SOURCE"
      DELEGATION_BUDGET_EXCEEDED = "DELEGATION_BUDGET_EXCEEDED"
      DELEGATION_CUMULATIVE_BUDGET_EXCEEDED = "DELEGATION_CUMULATIVE_BUDGET_EXCEEDED"
      DELEGATION_CYCLE = "DELEGATION_CYCLE"
      DELEGATION_SOURCE_REVOKED = "DELEGATION_SOURCE_REVOKED"
      DELEGATION_SOURCE_EXPIRED = "DELEGATION_SOURCE_EXPIRED"
      DELEGATION_SOURCE_NOT_YET_VALID = "DELEGATION_SOURCE_NOT_YET_VALID"
      DELEGATION_LATE_ARRIVAL = "DELEGATION_LATE_ARRIVAL"
      DELEGATION_EXPIRED = "DELEGATION_EXPIRED"
      DELEGATION_NOT_YET_VALID = "DELEGATION_NOT_YET_VALID"

      EMERGENCY_TIMEOUT = "EMERGENCY_TIMEOUT"
      EMERGENCY_SCOPE_NOT_ALLOWED = "EMERGENCY_SCOPE_NOT_ALLOWED"

      DENIAL_PRIORITY = {
        REVOKED => 100,
        DELEGATION_SOURCE_REVOKED => 99,
        DELEGATION_LATE_ARRIVAL => 95,
        DELEGATION_BROADER_THAN_SOURCE => 90,
        DELEGATION_DURATION_EXCEEDS_SOURCE => 88,
        DELEGATION_BUDGET_EXCEEDED => 86,
        DELEGATION_CUMULATIVE_BUDGET_EXCEEDED => 85,
        DELEGATION_CYCLE => 80,
        EXPIRED => 70,
        DELEGATION_SOURCE_EXPIRED => 69,
        DELEGATION_EXPIRED => 68,
        NOT_YET_VALID => 60,
        DELEGATION_SOURCE_NOT_YET_VALID => 59,
        DELEGATION_NOT_YET_VALID => 58,
        WITNESS_MISSING => 50,
        SCOPE_NOT_GRANTED => 40,
        DELEGATION_WITHOUT_SOURCE => 30,
        EMERGENCY_TIMEOUT => 20,
        EMERGENCY_SCOPE_NOT_ALLOWED => 10,
        NO_CONSENT => 0
      }.freeze

      def self.authorized?(code)
        code == AUTHORIZED || code == EMERGENCY_AUTHORIZED
      end

      def self.strongest(codes)
        codes.compact.max_by { |c| DENIAL_PRIORITY.fetch(c, -1) }
      end
    end
  end
end
